/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in (issue access + refresh)
         * @description Validates credentials and returns a short-lived access JWT. A refresh token is set as an HttpOnly, Secure, SameSite cookie (rotation is [MVP]). Errors: 401 on bad credentials, 403 if the user's status is not ACTIVE.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new company user (status PENDING)
         * @description Creates a user under an active company with status PENDING (awaits Company-Admin approval). Validations — unique email, valid contact number, valid PIN, distanceKm 0–200, password strength, company must be active, one company per user.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm an email-verification token */
        post: operations["verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate refresh token, issue a new access token
         * @description Uses the HttpOnly refresh cookie; rotates it and returns a fresh access token.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current refresh token */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a password-reset email */
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset password using a reset token */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change password (authenticated) */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current user's profile */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update the current user's profile (incl. distanceKm)
         * @description Partial update. `distanceKm` is the manually-entered home→office distance (0–200 km).
         */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/me/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user's bookings (paged) */
        get: operations["getMyBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user's in-app notifications (paged) */
        get: operations["getMyNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark a notification as read */
        patch: operations["markNotificationRead"];
        trace?: never;
    };
    "/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List companies (management) */
        get: operations["listCompanies"];
        put?: never;
        /** Create a company */
        post: operations["createCompany"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Public list of active companies (registration dropdown)
         * @description Public id+name subset of ACTIVE companies for the registration form.
         */
        get: operations["listActiveCompanies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get a company */
        get: operations["getCompany"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a company */
        patch: operations["updateCompany"];
        trace?: never;
    };
    "/companies/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Activate or deactivate a company */
        patch: operations["setCompanyStatus"];
        trace?: never;
    };
    "/companies/{id}/users": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * List users in a company
         * @description Super Admin for any company; Company Admin restricted to their own company (tenant-scoped).
         */
        get: operations["listCompanyUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/approval": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Approve or reject a pending user
         * @description Company Admin (own company). APPROVE → ACTIVE, REJECT → REJECTED.
         */
        patch: operations["setUserApproval"];
        trace?: never;
    };
    "/users/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Activate or deactivate a user */
        patch: operations["setUserStatus"];
        trace?: never;
    };
    "/companies/{id}/admins": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign a user as Company Admin */
        post: operations["assignCompanyAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List parking slots */
        get: operations["listSlots"];
        put?: never;
        /** Create a parking slot */
        post: operations["createSlot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slots/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a parking slot (type/status/attributes) */
        patch: operations["updateSlot"];
        trace?: never;
    };
    "/companies/{id}/quota": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get a company's quota rows (current + future) */
        get: operations["getCompanyQuota"];
        put?: never;
        /** Set a company's slot quota (effective-dated) */
        post: operations["setCompanyQuota"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{id}/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * List a company's quota blocks
         * @description Super Admin any company; Company Admin own company only; USER forbidden.
         */
        get: operations["listBlocks"];
        put?: never;
        /**
         * Block a count of the company's quota (with reason)
         * @description Super Admin any company; Company Admin own company only; USER forbidden.
         */
        post: operations["createBlock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blocks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a quota block (unblock)
         * @description Super Admin any company; Company Admin own company only; USER forbidden.
         */
        delete: operations["deleteBlock"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all system configuration (timings, weights, etc.) */
        get: operations["getConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update configuration values (timings/weights — D8)
         * @description Partial map of key→value (string values). Validates time ordering (primaryCutoff < primaryResultsBy ≤ commonPoolClose < commonPoolResultsBy) and numeric ranges; on success the scheduler reschedules. Every change is audited.
         */
        patch: operations["updateConfig"];
        trace?: never;
    };
    "/dashboard/super-admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Super Admin dashboard counts */
        get: operations["getSuperAdminDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/company-admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Company Admin dashboard counts (own company) */
        get: operations["getCompanyAdminDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** User dashboard (upcoming booking, status, cutoff countdown) */
        get: operations["getUserDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{type}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type: components["schemas"]["ReportType"];
            };
            cookie?: never;
        };
        /** Get a report (Later) */
        get: operations["getReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{type}/export": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type: components["schemas"]["ReportType"];
            };
            cookie?: never;
        };
        /** Export a report as CSV (Later; async for large sets) */
        get: operations["exportReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Standard success envelope. `data` is the resource/list; `meta` present only on list endpoints. */
        SuccessEnvelope: {
            /** @enum {boolean} */
            success: true;
            data: Record<string, never>;
            meta?: components["schemas"]["Pagination"];
        };
        /** @description Standard error envelope. */
        ErrorEnvelope: {
            /** @enum {boolean} */
            success: false;
            error: components["schemas"]["ErrorObject"];
        };
        ErrorObject: {
            code: components["schemas"]["ErrorCode"];
            message: string;
            details?: components["schemas"]["ErrorDetail"][];
        };
        ErrorDetail: {
            field: string;
            message: string;
        };
        /**
         * @description Canonical error codes (docs/phases-3-6-plan.md §3.2).
         * @enum {string}
         */
        ErrorCode: "VALIDATION_ERROR" | "UNAUTHENTICATED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "WINDOW_CLOSED" | "RATE_LIMITED" | "INTERNAL";
        Pagination: {
            page: number;
            pageSize: number;
            total: number;
        };
        /** @enum {string} */
        RoleName: "SUPER_ADMIN" | "COMPANY_ADMIN" | "USER";
        /** @enum {string} */
        UserStatus: "PENDING" | "ACTIVE" | "REJECTED" | "INACTIVE";
        /** @enum {string} */
        BookingType: "PRIMARY" | "COMMON_POOL";
        /** @enum {string} */
        BookingStatus: "DRAFT" | "SUBMITTED" | "CANCELLED" | "ALLOCATED" | "WAITLISTED" | "REJECTED" | "RELEASED" | "EXPIRED";
        /** @enum {string} */
        VehicleType: "CAR" | "BIKE" | "EV_CAR" | "EV_BIKE" | "OTHER";
        /** @enum {string} */
        NotificationChannel: "EMAIL" | "IN_APP" | "SMS" | "PUSH";
        /** @enum {string} */
        NotificationStatus: "PENDING" | "SENT" | "FAILED" | "READ";
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        AuthUser: {
            id: string;
            fullName: string;
            role: components["schemas"]["RoleName"];
            companyId: string;
            companyName: string;
        };
        AccessTokenData: {
            accessToken: string;
            /** @enum {string} */
            tokenType: "Bearer";
            /** @description Access-token lifetime in seconds. */
            expiresIn: number;
        };
        LoginResponseData: components["schemas"]["AccessTokenData"] & {
            user: components["schemas"]["AuthUser"];
        };
        RegisterRequest: {
            fullName: string;
            /** @description Must reference an ACTIVE company. */
            companyId: string;
            /** Format: email */
            email: string;
            contactNumber: string;
            address: string;
            pinCode: string;
            /** @description Manually-entered home→office distance in km (D6). Optional at registration. */
            distanceKm?: number | null;
            /** Format: password */
            password: string;
            /** Format: password */
            confirmPassword: string;
        };
        UserProfile: {
            id: string;
            fullName: string;
            /** Format: email */
            email: string;
            contactNumber: string;
            address: string;
            pinCode: string;
            distanceKm?: number | null;
            status: components["schemas"]["UserStatus"];
            emailVerified: boolean;
            companyId: string;
            companyName: string;
            role: components["schemas"]["RoleName"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        /** @description Partial update; all fields optional. */
        UpdateProfileRequest: {
            fullName?: string;
            contactNumber?: string;
            address?: string;
            pinCode?: string;
            distanceKm?: number | null;
        };
        Booking: {
            id: string;
            /** Format: date */
            bookingDate: string;
            bookingType: components["schemas"]["BookingType"];
            status: components["schemas"]["BookingStatus"];
            travelDistanceKm?: number | null;
            vehicleType?: components["schemas"]["VehicleType"];
            vehicleNumber?: string | null;
            carpoolMemberCount: number;
            specialRequirement?: string | null;
            allocationScore?: number | null;
            /** @description Slot number if ALLOCATED, else null. */
            allocatedSlotNumber?: string | null;
            /** Format: date-time */
            submittedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        Notification: {
            id: string;
            channel: components["schemas"]["NotificationChannel"];
            status: components["schemas"]["NotificationStatus"];
            subject: string;
            body: string;
            metadata?: {
                [key: string]: unknown;
            } | null;
            /** Format: date-time */
            sentAt?: string | null;
            /** Format: date-time */
            readAt?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        /** @enum {string} */
        CompanyStatus: "ACTIVE" | "INACTIVE";
        /** @enum {string} */
        SlotType: "STANDARD" | "ACCESSIBLE" | "EV_CHARGING" | "VISITOR" | "RESERVED";
        /** @enum {string} */
        SlotStatus: "AVAILABLE" | "ALLOCATED_TO_COMPANY" | "BLOCKED" | "BOOKED" | "COMMON_POOL" | "UNDER_MAINTENANCE" | "INACTIVE";
        /** @enum {string} */
        BlockReason: "RESERVED_VISITOR" | "RESERVED_LEADERSHIP" | "MAINTENANCE" | "COMPANY_EVENT" | "EMERGENCY" | "OTHER";
        /** @enum {string} */
        ApprovalDecision: "APPROVE" | "REJECT";
        Company: {
            id: string;
            name: string;
            code: string;
            status: components["schemas"]["CompanyStatus"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description Public subset for the registration dropdown. */
        CompanySummary: {
            id: string;
            name: string;
        };
        CreateCompanyRequest: {
            name: string;
            /** @description Short unique tenant code (e.g. ASSENT). */
            code: string;
        };
        UpdateCompanyRequest: {
            name?: string;
        };
        UpdateCompanyStatusRequest: {
            status: components["schemas"]["CompanyStatus"];
        };
        ApprovalRequest: {
            decision: components["schemas"]["ApprovalDecision"];
        };
        UpdateUserStatusRequest: {
            status: components["schemas"]["UserStatus"];
        };
        AssignAdminRequest: {
            userId: string;
        };
        ParkingSlot: {
            id: string;
            slotNumber: string;
            parkingAreaId: string;
            slotType: components["schemas"]["SlotType"];
            status: components["schemas"]["SlotStatus"];
            hasEvCharging: boolean;
            isAccessible: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateSlotRequest: {
            slotNumber: string;
            parkingAreaId: string;
            slotType?: components["schemas"]["SlotType"];
            /** @default false */
            hasEvCharging: boolean;
            /** @default false */
            isAccessible: boolean;
        };
        UpdateSlotRequest: {
            slotNumber?: string;
            slotType?: components["schemas"]["SlotType"];
            status?: components["schemas"]["SlotStatus"];
            hasEvCharging?: boolean;
            isAccessible?: boolean;
        };
        /** @description Effective-dated company slot quota (CompanySlotAllocation). */
        CompanyQuota: {
            id: string;
            companyId: string;
            slotCount: number;
            /** Format: date */
            effectiveFrom: string;
            /** Format: date */
            effectiveTo?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        CreateQuotaRequest: {
            slotCount: number;
            /** Format: date */
            effectiveFrom: string;
            /** Format: date */
            effectiveTo?: string | null;
        };
        SlotBlock: {
            id: string;
            companyId: string;
            blockedCount: number;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            reason: components["schemas"]["BlockReason"];
            reasonText?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        CreateBlockRequest: {
            blockedCount: number;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            reason: components["schemas"]["BlockReason"];
            reasonText?: string | null;
        };
        /** @enum {string} */
        ConfigValueType: "STRING" | "NUMBER" | "BOOLEAN" | "JSON" | "TIME";
        ConfigEntry: {
            key: string;
            value: string;
            valueType: components["schemas"]["ConfigValueType"];
            description?: string | null;
            /** Format: date-time */
            updatedAt?: string;
        };
        /** @description Partial map of config key → new value (all values as strings). */
        UpdateConfigRequest: {
            [key: string]: string;
        };
        SuperAdminDashboard: {
            totalParkingSlots?: number;
            totalActiveCompanies?: number;
            blockedSlots?: number;
            availableSlots?: number;
            primaryBookings?: number;
            commonPoolBookings?: number;
            waitlistCount?: number;
            dailyUtilizationPct?: number;
        };
        CompanyAdminDashboard: {
            /** @description Current effective quota. */
            totalCompanySlots?: number;
            availableCompanySlots?: number;
            blockedSlots?: number;
            bookedSlots?: number;
            commonPoolSlots?: number;
            totalBookingRequests?: number;
            allocatedUsers?: number;
            waitlistedUsers?: number;
            dailyUtilizationPct?: number;
        };
        UserDashboard: {
            /** @description Absent when the user has no upcoming booking. */
            upcomingBooking?: components["schemas"]["Booking"];
            cutoffCountdownSeconds?: number | null;
            previousBookingsCount?: number;
        };
        /** @enum {string} */
        ReportType: "daily-allocation" | "company-utilization" | "user-booking-history" | "requests-vs-allocations" | "common-pool-utilization" | "blocked-slot-history" | "released-slot-history" | "frequent-winners" | "frequent-waitlisted" | "carpool-participation" | "allocation-score-breakdown";
    };
    responses: {
        /** @description Success with a simple acknowledgement message. */
        MessageOk: {
            headers: {
                "X-Correlation-Id": components["headers"]["CorrelationId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": true,
                 *       "data": {
                 *         "message": "OK"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["SuccessEnvelope"] & {
                    data?: {
                        message?: string;
                    };
                };
            };
        };
        /** @description 400 — request validation failed. */
        ValidationError: {
            headers: {
                "X-Correlation-Id": components["headers"]["CorrelationId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": {
                 *         "code": "VALIDATION_ERROR",
                 *         "message": "Request validation failed",
                 *         "details": [
                 *           {
                 *             "field": "distanceKm",
                 *             "message": "must be between 0 and 200"
                 *           }
                 *         ]
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 401 — missing/invalid/expired access token or bad credentials. */
        Unauthorized: {
            headers: {
                "X-Correlation-Id": components["headers"]["CorrelationId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": {
                 *         "code": "UNAUTHENTICATED",
                 *         "message": "Invalid credentials"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 403 — role or tenant-scope violation (or inactive account). */
        Forbidden: {
            headers: {
                "X-Correlation-Id": components["headers"]["CorrelationId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": {
                 *         "code": "FORBIDDEN",
                 *         "message": "Account is not active"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 404 — resource absent or not visible to the tenant. */
        NotFound: {
            headers: {
                "X-Correlation-Id": components["headers"]["CorrelationId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": {
                 *         "code": "NOT_FOUND",
                 *         "message": "Resource not found"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 409 — duplicate resource. */
        Conflict: {
            headers: {
                "X-Correlation-Id": components["headers"]["CorrelationId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": {
                 *         "code": "CONFLICT",
                 *         "message": "Email already registered"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 429 — too many requests. */
        RateLimited: {
            headers: {
                "X-Correlation-Id": components["headers"]["CorrelationId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": {
                 *         "code": "RATE_LIMITED",
                 *         "message": "Too many requests"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        /** @description 1-based page number. */
        PageParam: number;
        /** @description Items per page (max 100). */
        PageSizeParam: number;
        /** @description Field to sort by. */
        SortParam: string;
        /** @description Sort direction. */
        OrderParam: "asc" | "desc";
    };
    requestBodies: never;
    headers: {
        /** @description Request/response correlation id (echoed into AuditLog). */
        CorrelationId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "email": "aditi@assent.example",
                 *       "password": "ChangeMe#12345"
                 *     }
                 */
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated. Refresh token set via Set-Cookie. */
            200: {
                headers: {
                    "X-Correlation-Id": components["headers"]["CorrelationId"];
                    /** @description HttpOnly refresh-token cookie (e.g. `refreshToken=…; HttpOnly; Secure; SameSite=Strict`) */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": true,
                     *       "data": {
                     *         "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
                     *         "tokenType": "Bearer",
                     *         "expiresIn": 900,
                     *         "user": {
                     *           "id": "usr_123",
                     *           "fullName": "Aditi Rao",
                     *           "role": "USER",
                     *           "companyId": "cmp_1",
                     *           "companyName": "Assent"
                     *         }
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["LoginResponseData"];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Registration accepted; verification email dispatched. */
            201: {
                headers: {
                    "X-Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["UserProfile"];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            409: components["responses"]["Conflict"];
        };
    };
    verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                };
            };
        };
        responses: {
            200: components["responses"]["MessageOk"];
            400: components["responses"]["ValidationError"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New access token issued; refresh cookie rotated. */
            200: {
                headers: {
                    "X-Correlation-Id": components["headers"]["CorrelationId"];
                    /** @description Rotated HttpOnly refresh-token cookie */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["AccessTokenData"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["MessageOk"];
            401: components["responses"]["Unauthorized"];
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            200: components["responses"]["MessageOk"];
            400: components["responses"]["ValidationError"];
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                    /** Format: password */
                    newPassword: string;
                };
            };
        };
        responses: {
            200: components["responses"]["MessageOk"];
            400: components["responses"]["ValidationError"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: password */
                    currentPassword: string;
                    /** Format: password */
                    newPassword: string;
                };
            };
        };
        responses: {
            200: components["responses"]["MessageOk"];
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current profile */
            200: {
                headers: {
                    "X-Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["UserProfile"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Updated profile */
            200: {
                headers: {
                    "X-Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["UserProfile"];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getMyBookings: {
        parameters: {
            query?: {
                /** @description 1-based page number. */
                page?: components["parameters"]["PageParam"];
                /** @description Items per page (max 100). */
                pageSize?: components["parameters"]["PageSizeParam"];
                /** @description Field to sort by. */
                sort?: components["parameters"]["SortParam"];
                /** @description Sort direction. */
                order?: components["parameters"]["OrderParam"];
                /** @description Optional filter by booking status */
                status?: components["schemas"]["BookingStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paged list of the user's bookings */
            200: {
                headers: {
                    "X-Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["Booking"][];
                        meta: components["schemas"]["Pagination"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMyNotifications: {
        parameters: {
            query?: {
                /** @description 1-based page number. */
                page?: components["parameters"]["PageParam"];
                /** @description Items per page (max 100). */
                pageSize?: components["parameters"]["PageSizeParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paged list of notifications */
            200: {
                headers: {
                    "X-Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["Notification"][];
                        meta: components["schemas"]["Pagination"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    markNotificationRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notification marked read */
            200: {
                headers: {
                    "X-Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["Notification"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listCompanies: {
        parameters: {
            query?: {
                /** @description 1-based page number. */
                page?: components["parameters"]["PageParam"];
                /** @description Items per page (max 100). */
                pageSize?: components["parameters"]["PageSizeParam"];
                status?: components["schemas"]["CompanyStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paged list of companies */
            200: {
                headers: {
                    "X-Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["Company"][];
                        meta: components["schemas"]["Pagination"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createCompany: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCompanyRequest"];
            };
        };
        responses: {
            /** @description Company created */
            201: {
                headers: {
                    "X-Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["Company"];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    listActiveCompanies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active companies (id + name) */
            200: {
                headers: {
                    "X-Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["CompanySummary"][];
                    };
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    getCompany: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Company */
            200: {
                headers: {
                    "X-Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["Company"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateCompany: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCompanyRequest"];
            };
        };
        responses: {
            /** @description Updated company */
            200: {
                headers: {
                    "X-Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["Company"];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    setCompanyStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCompanyStatusRequest"];
            };
        };
        responses: {
            /** @description Updated company */
            200: {
                headers: {
                    "X-Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["Company"];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listCompanyUsers: {
        parameters: {
            query?: {
                /** @description 1-based page number. */
                page?: components["parameters"]["PageParam"];
                /** @description Items per page (max 100). */
                pageSize?: components["parameters"]["PageSizeParam"];
                status?: components["schemas"]["UserStatus"];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paged list of company users */
            200: {
                headers: {
                    "X-Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["UserProfile"][];
                        meta: components["schemas"]["Pagination"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    setUserApproval: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalRequest"];
            };
        };
        responses: {
            /** @description Updated user */
            200: {
                headers: {
                    "X-Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["UserProfile"];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    setUserStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserStatusRequest"];
            };
        };
        responses: {
            /** @description Updated user */
            200: {
                headers: {
                    "X-Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["UserProfile"];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    assignCompanyAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignAdminRequest"];
            };
        };
        responses: {
            200: components["responses"]["MessageOk"];
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listSlots: {
        parameters: {
            query?: {
                /** @description 1-based page number. */
                page?: components["parameters"]["PageParam"];
                /** @description Items per page (max 100). */
                pageSize?: components["parameters"]["PageSizeParam"];
                status?: components["schemas"]["SlotStatus"];
                parkingAreaId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paged list of slots */
            200: {
                headers: {
                    "X-Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["ParkingSlot"][];
                        meta: components["schemas"]["Pagination"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createSlot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSlotRequest"];
            };
        };
        responses: {
            /** @description Slot created */
            201: {
                headers: {
                    "X-Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["ParkingSlot"];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    updateSlot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSlotRequest"];
            };
        };
        responses: {
            /** @description Updated slot */
            200: {
                headers: {
                    "X-Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["ParkingSlot"];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getCompanyQuota: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Effective-dated quota rows */
            200: {
                headers: {
                    "X-Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["CompanyQuota"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    setCompanyQuota: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateQuotaRequest"];
            };
        };
        responses: {
            /** @description Quota row created */
            201: {
                headers: {
                    "X-Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["CompanyQuota"];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listBlocks: {
        parameters: {
            query?: {
                /** @description 1-based page number. */
                page?: components["parameters"]["PageParam"];
                /** @description Items per page (max 100). */
                pageSize?: components["parameters"]["PageSizeParam"];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paged list of blocks */
            200: {
                headers: {
                    "X-Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["SlotBlock"][];
                        meta: components["schemas"]["Pagination"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createBlock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBlockRequest"];
            };
        };
        responses: {
            /** @description Block created */
            201: {
                headers: {
                    "X-Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["SlotBlock"];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteBlock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["MessageOk"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All configuration entries */
            200: {
                headers: {
                    "X-Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["ConfigEntry"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    updateConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "booking.primaryCutoff": "18:30",
                 *       "allocation.distanceWeight": "0.6"
                 *     }
                 */
                "application/json": components["schemas"]["UpdateConfigRequest"];
            };
        };
        responses: {
            /** @description Updated configuration (full set) */
            200: {
                headers: {
                    "X-Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["ConfigEntry"][];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getSuperAdminDashboard: {
        parameters: {
            query?: {
                /** @description Business date for daily figures (defaults to today, IST). */
                date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Super Admin dashboard */
            200: {
                headers: {
                    "X-Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["SuperAdminDashboard"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getCompanyAdminDashboard: {
        parameters: {
            query?: {
                date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Company Admin dashboard */
            200: {
                headers: {
                    "X-Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["CompanyAdminDashboard"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getUserDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User dashboard */
            200: {
                headers: {
                    "X-Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["UserDashboard"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getReport: {
        parameters: {
            query?: {
                date?: string;
                dateFrom?: string;
                dateTo?: string;
                companyId?: string;
                userId?: string;
                slotId?: string;
                bookingType?: components["schemas"]["BookingType"];
                bookingStatus?: components["schemas"]["BookingStatus"];
                /** @description 1-based page number. */
                page?: components["parameters"]["PageParam"];
                /** @description Items per page (max 100). */
                pageSize?: components["parameters"]["PageSizeParam"];
            };
            header?: never;
            path: {
                type: components["schemas"]["ReportType"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Report rows (shape depends on report type) */
            200: {
                headers: {
                    "X-Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: {
                            [key: string]: unknown;
                        }[];
                        meta: components["schemas"]["Pagination"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    exportReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type: components["schemas"]["ReportType"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
}
